### ISSUE TITLE
币应该锁定为1，否则难以体现互赞本质。

### ISSUE THREAD

**Issue by augushong** [FTLIKON/EachStar#10]
这个币，应该锁定1比较好吧，
这样必须关注一个项目才能得到另一个人的关注。

否则得到别人的关注，却不需要关注别人。
局部币膨胀得太厉害，导致不去积极关注其他项目。

或者出现币消耗的太快，反而没有渠道得到币，导致没法获得更多的关注。

锁定为1时，能更好的体现出互赞的本质，

否则便成了信息发布平台了。

**Comment by FTLIKON** [comment]
准备开发eachStar新版了，感谢您的关注
