### ISSUE TITLE
添加了卡片，为什么gitee只有一页

### ISSUE THREAD

**Issue by CJayHe** [FTLIKON/EachStar#11]

**Comment by FTLIKON** [comment]
因为现在使用gitee版本的用户还比较少~ 等以后使用gitee版本的EachStar的用户多了就不只一页了！感谢使用哦

**Comment by CJayHe** [comment]
这不是数据量的问题呀。我上传的仓库在列表上看不到的。 是不是没做分页。

**Comment by FTLIKON** [comment]
您上传的仓库应该是被别人点赞过了，所以悬赏次数为0，在列表上就被隐藏了。
可以重新发布卡片，提高悬赏次数的设置，就能在列表看到啦
