### ISSUE TITLE
严重重复star的bug

### ISSUE THREAD

**Issue by OShuaLar** [FTLIKON/EachStar#15]
修改githubId可以重复star.
希望修复.
(对那几个少star的说抱歉)

**Comment by OShuaLar** [comment]
还有 网站的ssl证书过期了, 记得续期哦

**Comment by 743859910** [comment]
貌似凉凉了吧，我看网站上都是几百天以前的内容了

**Comment by FTLIKON** [comment]
网站的ssl正式已修复。准备开发eachStar新版了，感谢您的关注
